export const ENTITY_API_RESULT = [
    {
        "entity": "CAT",
        "employees": [
            {
                "firstName": "Molly",
                "lastName": "Maheras",
                "jobTitle": "Creative Director",
                "agencyName": "C&T",
                "entity": "CAT",
                "employeeId": "000001109",
                "baseCompPresent": 100000,
                "cashBonusPresent": 115000,
                "stockBonusPresent": 120000,
                "stockPremiumPresent": 132000,
                "totalBonusPresent": 247000,
                "baseCompPrevious": 100000,
                "cashBonusPrevious": 115000,
                "stockBonusPrevious": 30000,
                "stockPremiumPrevious": 33000,
                "totalBonusPrevious": 148000,
                "vesting": 0,
                "vestingPremiumPercentage": 0,
                "year": 2023,
                "costType": "SG",
                "retentionCurrentYear": 5000,
                "ssn": "1047",
                "fullName": "Molly Maheras",
                "emailAddress": "molly.maheras@wearekettle.com",
                "homeAddress": "613 Walnut St",
                "homeAddressCity": "Petaluma",
                "homeAddressStateCode": "CA",
                "homeAddressStateName": "California",
                "homeAddressZipCode": "94952",
                "homeAddressCountry": "United States",
                "countryOfPayrollTaxation": "United States",
                "birthDate": "1985-04-18T18:30:00.000+00:00",
                "hireDate": "2017-10-25T18:30:00.000+00:00",
                "agencyID": 13
            },
            {
                "firstName": "Olivier",
                "lastName": "Peyre",
                "jobTitle": "Creative Chair",
                "agencyName": "C&T",
                "entity": "CAT",
                "employeeId": "000000065",
                "baseCompPresent": 80000,
                "cashBonusPresent": 20000,
                "stockBonusPresent": 25000,
                "stockPremiumPresent": 27500,
                "totalBonusPresent": 47500,
                "baseCompPrevious": 80000,
                "cashBonusPrevious": 20000,
                "stockBonusPrevious": 30000,
                "stockPremiumPrevious": 33000,
                "totalBonusPrevious": 53000,
                "vesting": 0,
                "vestingPremiumPercentage": 0,
                "year": 2023,
                "costType": "SG",
                "retentionCurrentYear": 5000,
                "ssn": "1049",
                "fullName": "Olivier Peyre",
                "emailAddress": "opeyre@mac.com",
                "homeAddress": "3408 Larissa Drive",
                "homeAddressCity": "Los Angeles",
                "homeAddressStateCode": "CA",
                "homeAddressStateName": "California",
                "homeAddressZipCode": "90026",
                "homeAddressCountry": "US",
                "countryOfPayrollTaxation": "US",
                "birthDate": "1977-03-02T18:30:00.000+00:00",
                "hireDate": "2019-01-03T18:30:00.000+00:00",
                "agencyID": 13
            },
            {
                "firstName": "Molly",
                "lastName": "Maheras",
                "jobTitle": "Creative Director",
                "agencyName": "C&T",
                "entity": "CAT",
                "employeeId": "000000015",
                "baseCompPresent": 75000,
                "cashBonusPresent": 10000,
                "stockBonusPresent": 15000,
                "stockPremiumPresent": 16500,
                "totalBonusPresent": 26500,
                "baseCompPrevious": 75000,
                "cashBonusPrevious": 10000,
                "stockBonusPrevious": 30000,
                "stockPremiumPrevious": 33000,
                "totalBonusPrevious": 43000,
                "vesting": 0,
                "vestingPremiumPercentage": 0,
                "year": 2023,
                "costType": "SG",
                "retentionCurrentYear": 5000,
                "ssn": "1050",
                "fullName": "Molly Maheras",
                "emailAddress": "molly.maheras@wearekettle.com",
                "homeAddress": "613 Walnut Street",
                "homeAddressCity": "Petaluma",
                "homeAddressStateCode": "CA",
                "homeAddressStateName": "California",
                "homeAddressZipCode": "94952",
                "homeAddressCountry": "US",
                "countryOfPayrollTaxation": "US",
                "birthDate": "1985-04-18T18:30:00.000+00:00",
                "hireDate": "2019-01-04T18:30:00.000+00:00",
                "agencyID": 13
            },
            {
                "firstName": "Vincent",
                "lastName": "Quilici",
                "jobTitle": "Managing Director, Strategic Accounts",
                "agencyName": "C&T",
                "entity": "CAT",
                "employeeId": "000000841",
                "baseCompPresent": 90000,
                "cashBonusPresent": 120000,
                "stockBonusPresent": 125000,
                "stockPremiumPresent": 131250,
                "totalBonusPresent": 251250,
                "baseCompPrevious": 90000,
                "cashBonusPrevious": 120000,
                "stockBonusPrevious": 30000,
                "stockPremiumPrevious": 31500,
                "totalBonusPrevious": 151500,
                "vesting": 0,
                "vestingPremiumPercentage": 0,
                "year": 2023,
                "costType": "SG",
                "retentionCurrentYear": 5000,
                "ssn": "1048",
                "fullName": "Vincent Quilici",
                "emailAddress": " vince.quilici@codeandtheory.com",
                "homeAddress": "520 Este Madera Dr",
                "homeAddressCity": "Sonoma",
                "homeAddressStateCode": "CA",
                "homeAddressStateName": "California",
                "homeAddressZipCode": "95476",
                "homeAddressCountry": "US",
                "countryOfPayrollTaxation": "US",
                "birthDate": "1968-09-13T18:30:00.000+00:00",
                "hireDate": "2019-01-02T18:30:00.000+00:00",
                "agencyID": 13
            },
            {
                "firstName": "Benjamin",
                "lastName": "Berentson",
                "jobTitle": "Managing Director, New York",
                "agencyName": "C&T",
                "entity": "CAT",
                "employeeId": "000000206",
                "baseCompPresent": 180000,
                "cashBonusPresent": 5000,
                "stockBonusPresent": 10000,
                "stockPremiumPresent": 10500,
                "totalBonusPresent": 15500,
                "baseCompPrevious": 180000,
                "cashBonusPrevious": 5000,
                "stockBonusPrevious": 100000,
                "stockPremiumPrevious": 105000,
                "totalBonusPrevious": 110000,
                "vesting": 0,
                "vestingPremiumPercentage": 0,
                "year": 2023,
                "costType": "SG",
                "retentionCurrentYear": 5000,
                "ssn": "1051",
                "fullName": "Benjamin Berentson",
                "emailAddress": "ben.berentson@codeandtheory.com",
                "homeAddress": "100 Stephen Mather Rd",
                "homeAddressCity": "Darien",
                "homeAddressStateCode": "CT",
                "homeAddressStateName": null,
                "homeAddressZipCode": "6820",
                "homeAddressCountry": "US",
                "countryOfPayrollTaxation": "US",
                "birthDate": "1977-12-07T18:30:00.000+00:00",
                "hireDate": "2019-01-05T18:30:00.000+00:00",
                "agencyID": 13
            },
            {
                "firstName": "Harika",
                "lastName": "Inal",
                "jobTitle": "Chief Financial Officer",
                "agencyName": "C&T",
                "entity": "CAT",
                "employeeId": "000001031",
                "baseCompPresent": 100000,
                "cashBonusPresent": 2500,
                "stockBonusPresent": 7500,
                "stockPremiumPresent": 7875,
                "totalBonusPresent": 10375,
                "baseCompPrevious": 100000,
                "cashBonusPrevious": 2500,
                "stockBonusPrevious": 105000,
                "stockPremiumPrevious": 110250,
                "totalBonusPrevious": 112750,
                "vesting": 0,
                "vestingPremiumPercentage": 0,
                "year": 2023,
                "costType": "SG",
                "retentionCurrentYear": 5000,
                "ssn": "1052",
                "fullName": "Harika Inal",
                "emailAddress": "harika.inal@codeandtheory.com",
                "homeAddress": "4126 SW 12th Pl",
                "homeAddressCity": "Cape Coral",
                "homeAddressStateCode": "FL",
                "homeAddressStateName": null,
                "homeAddressZipCode": "33914",
                "homeAddressCountry": "US",
                "countryOfPayrollTaxation": "US",
                "birthDate": "1979-10-08T18:30:00.000+00:00",
                "hireDate": "2019-01-07T18:30:00.000+00:00",
                "agencyID": 13
            }
        ]
    },
    {
        "entity": "KTL",
        "employees": [
            {
                "firstName": "Molly",
                "lastName": "Maheras",
                "jobTitle": "Creative Director",
                "agencyName": "C&T",
                "entity": "KTL",
                "employeeId": "000001109",
                "baseCompPresent": 100000,
                "cashBonusPresent": 115000,
                "stockBonusPresent": 120000,
                "stockPremiumPresent": 132000,
                "totalBonusPresent": 247000,
                "baseCompPrevious": 100000,
                "cashBonusPrevious": 115000,
                "stockBonusPrevious": 30000,
                "stockPremiumPrevious": 33000,
                "totalBonusPrevious": 148000,
                "vesting": 0,
                "vestingPremiumPercentage": 0,
                "year": 2023,
                "costType": "SG",
                "retentionCurrentYear": 5000,
                "ssn": "1047",
                "fullName": "Molly Maheras",
                "emailAddress": "molly.maheras@wearekettle.com",
                "homeAddress": "613 Walnut St",
                "homeAddressCity": "Petaluma",
                "homeAddressStateCode": "CA",
                "homeAddressStateName": "California",
                "homeAddressZipCode": "94952",
                "homeAddressCountry": "United States",
                "countryOfPayrollTaxation": "United States",
                "birthDate": "1985-04-18T18:30:00.000+00:00",
                "hireDate": "2017-10-25T18:30:00.000+00:00",
                "agencyID": 13
            },
            {
                "firstName": "Olivier",
                "lastName": "Peyre",
                "jobTitle": "Creative Chair",
                "agencyName": "C&T",
                "entity": "KTL",
                "employeeId": "000000065",
                "baseCompPresent": 80000,
                "cashBonusPresent": 20000,
                "stockBonusPresent": 25000,
                "stockPremiumPresent": 27500,
                "totalBonusPresent": 47500,
                "baseCompPrevious": 80000,
                "cashBonusPrevious": 20000,
                "stockBonusPrevious": 30000,
                "stockPremiumPrevious": 33000,
                "totalBonusPrevious": 53000,
                "vesting": 0,
                "vestingPremiumPercentage": 0,
                "year": 2023,
                "costType": "SG",
                "retentionCurrentYear": 5000,
                "ssn": "1049",
                "fullName": "Olivier Peyre",
                "emailAddress": "opeyre@mac.com",
                "homeAddress": "3408 Larissa Drive",
                "homeAddressCity": "Los Angeles",
                "homeAddressStateCode": "CA",
                "homeAddressStateName": "California",
                "homeAddressZipCode": "90026",
                "homeAddressCountry": "US",
                "countryOfPayrollTaxation": "US",
                "birthDate": "1977-03-02T18:30:00.000+00:00",
                "hireDate": "2019-01-03T18:30:00.000+00:00",
                "agencyID": 13
            },
            {
                "firstName": "Molly",
                "lastName": "Maheras",
                "jobTitle": "Creative Director",
                "agencyName": "C&T",
                "entity": "KTL",
                "employeeId": "000000015",
                "baseCompPresent": 75000,
                "cashBonusPresent": 10000,
                "stockBonusPresent": 15000,
                "stockPremiumPresent": 16500,
                "totalBonusPresent": 26500,
                "baseCompPrevious": 75000,
                "cashBonusPrevious": 10000,
                "stockBonusPrevious": 30000,
                "stockPremiumPrevious": 33000,
                "totalBonusPrevious": 43000,
                "vesting": 0,
                "vestingPremiumPercentage": 0,
                "year": 2023,
                "costType": "SG",
                "retentionCurrentYear": 5000,
                "ssn": "1050",
                "fullName": "Molly Maheras",
                "emailAddress": "molly.maheras@wearekettle.com",
                "homeAddress": "613 Walnut Street",
                "homeAddressCity": "Petaluma",
                "homeAddressStateCode": "CA",
                "homeAddressStateName": "California",
                "homeAddressZipCode": "94952",
                "homeAddressCountry": "US",
                "countryOfPayrollTaxation": "US",
                "birthDate": "1985-04-18T18:30:00.000+00:00",
                "hireDate": "2019-01-04T18:30:00.000+00:00",
                "agencyID": 13
            },
            {
                "firstName": "Vincent",
                "lastName": "Quilici",
                "jobTitle": "Managing Director, Strategic Accounts",
                "agencyName": "C&T",
                "entity": "KTL",
                "employeeId": "000000841",
                "baseCompPresent": 90000,
                "cashBonusPresent": 120000,
                "stockBonusPresent": 125000,
                "stockPremiumPresent": 131250,
                "totalBonusPresent": 251250,
                "baseCompPrevious": 90000,
                "cashBonusPrevious": 120000,
                "stockBonusPrevious": 30000,
                "stockPremiumPrevious": 31500,
                "totalBonusPrevious": 151500,
                "vesting": 0,
                "vestingPremiumPercentage": 0,
                "year": 2023,
                "costType": "SG",
                "retentionCurrentYear": 5000,
                "ssn": "1048",
                "fullName": "Vincent Quilici",
                "emailAddress": " vince.quilici@codeandtheory.com",
                "homeAddress": "520 Este Madera Dr",
                "homeAddressCity": "Sonoma",
                "homeAddressStateCode": "CA",
                "homeAddressStateName": "California",
                "homeAddressZipCode": "95476",
                "homeAddressCountry": "US",
                "countryOfPayrollTaxation": "US",
                "birthDate": "1968-09-13T18:30:00.000+00:00",
                "hireDate": "2019-01-02T18:30:00.000+00:00",
                "agencyID": 13
            },
            {
                "firstName": "Benjamin",
                "lastName": "Berentson",
                "jobTitle": "Managing Director, New York",
                "agencyName": "C&T",
                "entity": "KTL",
                "employeeId": "000000206",
                "baseCompPresent": 180000,
                "cashBonusPresent": 5000,
                "stockBonusPresent": 10000,
                "stockPremiumPresent": 10500,
                "totalBonusPresent": 15500,
                "baseCompPrevious": 180000,
                "cashBonusPrevious": 5000,
                "stockBonusPrevious": 100000,
                "stockPremiumPrevious": 105000,
                "totalBonusPrevious": 110000,
                "vesting": 0,
                "vestingPremiumPercentage": 0,
                "year": 2023,
                "costType": "SG",
                "retentionCurrentYear": 5000,
                "ssn": "1051",
                "fullName": "Benjamin Berentson",
                "emailAddress": "ben.berentson@codeandtheory.com",
                "homeAddress": "100 Stephen Mather Rd",
                "homeAddressCity": "Darien",
                "homeAddressStateCode": "CT",
                "homeAddressStateName": null,
                "homeAddressZipCode": "6820",
                "homeAddressCountry": "US",
                "countryOfPayrollTaxation": "US",
                "birthDate": "1977-12-07T18:30:00.000+00:00",
                "hireDate": "2019-01-05T18:30:00.000+00:00",
                "agencyID": 13
            },
            {
                "firstName": "Harika",
                "lastName": "Inal",
                "jobTitle": "Chief Financial Officer",
                "agencyName": "C&T",
                "entity": "KTL",
                "employeeId": "000001031",
                "baseCompPresent": 100000,
                "cashBonusPresent": 2500,
                "stockBonusPresent": 7500,
                "stockPremiumPresent": 7875,
                "totalBonusPresent": 10375,
                "baseCompPrevious": 100000,
                "cashBonusPrevious": 2500,
                "stockBonusPrevious": 105000,
                "stockPremiumPrevious": 110250,
                "totalBonusPrevious": 112750,
                "vesting": 0,
                "vestingPremiumPercentage": 0,
                "year": 2023,
                "costType": "SG",
                "retentionCurrentYear": 5000,
                "ssn": "1052",
                "fullName": "Harika Inal",
                "emailAddress": "harika.inal@codeandtheory.com",
                "homeAddress": "4126 SW 12th Pl",
                "homeAddressCity": "Cape Coral",
                "homeAddressStateCode": "FL",
                "homeAddressStateName": null,
                "homeAddressZipCode": "33914",
                "homeAddressCountry": "US",
                "countryOfPayrollTaxation": "US",
                "birthDate": "1979-10-08T18:30:00.000+00:00",
                "hireDate": "2019-01-07T18:30:00.000+00:00",
                "agencyID": 13
            }
        ]
    }
]